package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Courier;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CourierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    int insert(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    Courier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    List<Courier> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    int updateByPrimaryKey(Courier record);

    Courier selectByCompanyName(@Param("companyName") String companyName);
}