package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Courier;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CourierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    int deleteByPrimaryKey(String companyname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    int insert(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    Courier selectByPrimaryKey(String companyname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    List<Courier> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    int updateByPrimaryKey(Courier record);
}