package lt.vu.mybatis.dao;

import java.util.List;

import lt.vu.mybatis.model.Courier;
import lt.vu.mybatis.model.CourierSenders;
import lt.vu.mybatis.model.Dispatch;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CourierSendersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER_SENDERS
     *
     * @mbg.generated Fri Feb 26 12:26:34 GMT+02:00 2021
     */
    int insert(CourierSenders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER_SENDERS
     *
     * @mbg.generated Fri Feb 26 12:26:34 GMT+02:00 2021
     */
    List<CourierSenders> selectAll();

    List<Courier> getCouriers(String name);
}