package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Dispatch;
import org.mybatis.cdi.Mapper;

@Mapper
public interface DispatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISPATCH
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    int deleteByPrimaryKey(String dispatchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISPATCH
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    int insert(Dispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISPATCH
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    Dispatch selectByPrimaryKey(String dispatchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISPATCH
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    List<Dispatch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DISPATCH
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    int updateByPrimaryKey(Dispatch record);

    List<Dispatch> selectBySender(String name);
}