package lt.vu.mybatis.dao;

import java.util.List;

import lt.vu.mybatis.model.Courier;
import lt.vu.mybatis.model.Dispatch;
import lt.vu.mybatis.model.Sender;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SenderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SENDER
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SENDER
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    int insert(Sender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SENDER
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    Sender selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SENDER
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    List<Sender> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SENDER
     *
     * @mbg.generated Sat Feb 20 16:34:04 GMT+02:00 2021
     */
    int updateByPrimaryKey(Sender record);
}