package lt.vu.mybatis.model;

public class Courier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.COMPANYNAME
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.CODE
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURIER.COMPANYNAME
     *
     * @return the value of PUBLIC.COURIER.COMPANYNAME
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURIER.COMPANYNAME
     *
     * @param companyname the value for PUBLIC.COURIER.COMPANYNAME
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURIER.CODE
     *
     * @return the value of PUBLIC.COURIER.CODE
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURIER.CODE
     *
     * @param code the value for PUBLIC.COURIER.CODE
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public void setCode(String code) {
        this.code = code;
    }
}