package lt.vu.mybatis.model;

public class CourierSenders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER_SENDERS.NAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER_SENDERS.COMPANYNAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    private String companyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURIER_SENDERS.NAME
     *
     * @return the value of PUBLIC.COURIER_SENDERS.NAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURIER_SENDERS.NAME
     *
     * @param name the value for PUBLIC.COURIER_SENDERS.NAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURIER_SENDERS.COMPANYNAME
     *
     * @return the value of PUBLIC.COURIER_SENDERS.COMPANYNAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURIER_SENDERS.COMPANYNAME
     *
     * @param companyname the value for PUBLIC.COURIER_SENDERS.COMPANYNAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }
}