package lt.vu.mybatis.model;

import java.util.List;

public class Courier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.ID
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.CODE
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.COMPANYNAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    private String companyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURIER.ID
     *
     * @return the value of PUBLIC.COURIER.ID
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURIER.ID
     *
     * @param id the value for PUBLIC.COURIER.ID
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURIER.CODE
     *
     * @return the value of PUBLIC.COURIER.CODE
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURIER.CODE
     *
     * @param code the value for PUBLIC.COURIER.CODE
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURIER.COMPANYNAME
     *
     * @return the value of PUBLIC.COURIER.COMPANYNAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURIER.COMPANYNAME
     *
     * @param companyname the value for PUBLIC.COURIER.COMPANYNAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    private List<Dispatch> dispatches;

    public List<Dispatch> getDispatches() { return this.dispatches; }

    public void setDispatches(List<Dispatch> dispatches) {
        this.dispatches = dispatches;
    }

}