package lt.vu.mybatis.model;

public class Dispatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.DISPATCHID
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    private String dispatchid;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.COURIERSERVICE_COMPANYNAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    private String courierserviceCompanyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.SENDER_NAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    private String senderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.COURIER
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    private String courier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.SENDER
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    private String sender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.DISPATCHID
     *
     * @return the value of PUBLIC.DISPATCH.DISPATCHID
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public String getDispatchid() {
        return dispatchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.DISPATCHID
     *
     * @param dispatchid the value for PUBLIC.DISPATCH.DISPATCHID
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public void setDispatchid(String dispatchid) {
        this.dispatchid = dispatchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.COURIERSERVICE_COMPANYNAME
     *
     * @return the value of PUBLIC.DISPATCH.COURIERSERVICE_COMPANYNAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public String getCourierserviceCompanyname() {
        return courierserviceCompanyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.COURIERSERVICE_COMPANYNAME
     *
     * @param courierserviceCompanyname the value for PUBLIC.DISPATCH.COURIERSERVICE_COMPANYNAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public void setCourierserviceCompanyname(String courierserviceCompanyname) {
        this.courierserviceCompanyname = courierserviceCompanyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.SENDER_NAME
     *
     * @return the value of PUBLIC.DISPATCH.SENDER_NAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.SENDER_NAME
     *
     * @param senderName the value for PUBLIC.DISPATCH.SENDER_NAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.COURIER
     *
     * @return the value of PUBLIC.DISPATCH.COURIER
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public String getCourier() {
        return courier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.COURIER
     *
     * @param courier the value for PUBLIC.DISPATCH.COURIER
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public void setCourier(String courier) {
        this.courier = courier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.SENDER
     *
     * @return the value of PUBLIC.DISPATCH.SENDER
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.SENDER
     *
     * @param sender the value for PUBLIC.DISPATCH.SENDER
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public void setSender(String sender) {
        this.sender = sender;
    }
}