package lt.vu.mybatis.model;

public class Dispatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.DISPATCHID
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    private String dispatchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.RECEIVERADDRESS
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    private String receiveraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.RECEIVER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.STATUS
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.COURIER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    private String courier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DISPATCH.SENDER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    private String sender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.DISPATCHID
     *
     * @return the value of PUBLIC.DISPATCH.DISPATCHID
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public String getDispatchid() {
        return dispatchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.DISPATCHID
     *
     * @param dispatchid the value for PUBLIC.DISPATCH.DISPATCHID
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public void setDispatchid(String dispatchid) {
        this.dispatchid = dispatchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.RECEIVERADDRESS
     *
     * @return the value of PUBLIC.DISPATCH.RECEIVERADDRESS
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public String getReceiveraddress() {
        return receiveraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.RECEIVERADDRESS
     *
     * @param receiveraddress the value for PUBLIC.DISPATCH.RECEIVERADDRESS
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public void setReceiveraddress(String receiveraddress) {
        this.receiveraddress = receiveraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.RECEIVER
     *
     * @return the value of PUBLIC.DISPATCH.RECEIVER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.RECEIVER
     *
     * @param receiver the value for PUBLIC.DISPATCH.RECEIVER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.STATUS
     *
     * @return the value of PUBLIC.DISPATCH.STATUS
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.STATUS
     *
     * @param status the value for PUBLIC.DISPATCH.STATUS
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.COURIER
     *
     * @return the value of PUBLIC.DISPATCH.COURIER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public String getCourier() {
        return courier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.COURIER
     *
     * @param courier the value for PUBLIC.DISPATCH.COURIER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public void setCourier(String courier) {
        this.courier = courier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DISPATCH.SENDER
     *
     * @return the value of PUBLIC.DISPATCH.SENDER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DISPATCH.SENDER
     *
     * @param sender the value for PUBLIC.DISPATCH.SENDER
     *
     * @mbg.generated Tue Feb 16 15:27:03 GMT+02:00 2021
     */
    public void setSender(String sender) {
        this.sender = sender;
    }
}