package lt.vu.mybatis.model;

public class Sender {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SENDER.NAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SENDER.NAME
     *
     * @return the value of PUBLIC.SENDER.NAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SENDER.NAME
     *
     * @param name the value for PUBLIC.SENDER.NAME
     *
     * @mbg.generated Sun Feb 14 14:14:37 GMT+02:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}