package lt.vu.mybatis.model;

import lt.vu.mybatis.dao.CourierMapper;

import java.util.List;

public class Sender {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SENDER.ID
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SENDER.ADDRESS
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SENDER.NAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SENDER.ID
     *
     * @return the value of PUBLIC.SENDER.ID
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SENDER.ID
     *
     * @param id the value for PUBLIC.SENDER.ID
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SENDER.ADDRESS
     *
     * @return the value of PUBLIC.SENDER.ADDRESS
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SENDER.ADDRESS
     *
     * @param address the value for PUBLIC.SENDER.ADDRESS
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SENDER.NAME
     *
     * @return the value of PUBLIC.SENDER.NAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SENDER.NAME
     *
     * @param name the value for PUBLIC.SENDER.NAME
     *
     * @mbg.generated Mon Mar 22 18:19:05 GMT+02:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }
    public List<Courier> courierServices;
    public void setCourierServices(List<Courier> courierServices) {
        this.courierServices = courierServices;
    }
}